debug: true
server:
  port: 8080
spring:
  profiles:
    active: local
  datasource:
    hikari:
      driver-class-name:
      jdbc-url:
      username:
      password:
      connectionTestQuery: select 1 
      minimumIdle: 1
      maximumPoolSize: 3
  #jackson:
  #  serialization:
  #    write-dates-as-timestamp: true
  #    INDENT_OUTPUT: true
  mvc:
    static-path-pattern: static/**
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

web-config:


# local
---
spring:
  profiles: local
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  h2:
    console:
      enabled: true
      path: /db
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:file:./db;AUTO_SERVER=TRUE
      username: sa
      password:
      connectionTestQuery: select 1
